### ISSUE TITLE
RecyclerViewにおいて、データを追加する場合は、notifyItemRangeInsertedを使う

### ISSUE THREAD

**Issue by taku-kw** [taku-kw/Qiita#3]
<指摘コメント>

https://github.com/taku-kw/Qiita/pull/2#discussion_r921294913

<該当コード>

       model.articleList.observe(viewLifecycleOwner, Observer { list ->
            val tempAdapter = articleListView.adapter as ArticleListAdapter
            tempAdapter.setArticleList(list)
            tempAdapter.notifyDataSetChanged() // ここ！

**Comment by shinya-takano** [comment]
参考の記事はこちらです。
https://qiita.com/sussan0416/items/e7d68a208f71b3b95f8f

**Comment by taku-kw** [comment]
コードを修正。
プルリクエストを作成。
https://github.com/taku-kw/Qiita/pull/8

**Comment by taku-kw** [comment]
mainへマージ。
このissueはクローズする。
